name: kai-lang
version: 0.1.1
description: A minimal, typed expression language implemented in Haskell
homepage: https://github.com/bikatr7/kai
license: AGPL-3.0-only
author: Kaden Bilyeu (Bikatr7)
maintainer: bikatr7@proton.me

dependencies:
  - base >= 4.7 && < 5
  - yesod
  - yesod-core
  - yesod-static
  - yesod-form
  - text
  - shakespeare
  - warp
  - aeson
  - containers
  - bytestring
  - megaparsec
  - parser-combinators
  - hspec
  - QuickCheck

library:
  source-dirs: src
  exposed-modules:
    - Syntax
    - Parser
    - Evaluator
    - TypeChecker

executables:
  kai-website:
    main: Main.hs
    source-dirs: website
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory

  kai:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  kai-test:
    main: Spec.hs
    source-dirs: 
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - QuickCheck
      - kai-lang
      - directory
      - filepath
    build-tools:
      - hspec-discover
