name: kai-lang
version: 0.1.0.0
description: A minimal, typed expression language implemented in Haskell
homepage: https://github.com/kbilyeu/kai
license: MIT
author: Kai Bilyeu
maintainer: kbilyeu@example.com

dependencies:
  - base >= 4.7 && < 5
  - yesod
  - yesod-core
  - yesod-static
  - yesod-form
  - text
  - shakespeare
  - warp
  - aeson
  - containers
  - bytestring
  - megaparsec
  - parser-combinators

executables:
  kai-website:
    main: Main.hs
    source-dirs: website
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory

  kai:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
