name: haskell-website
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - yesod
  - yesod-core
  - yesod-static
  - yesod-form
  - text
  - shakespeare
  - warp
  - aeson
  - containers
  - bytestring

executables:
  haskell-website:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
